/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/site'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard/settings'
import { Route as DashboardResumeRouteImport } from './routes/_dashboard/resume'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardJobsRouteImport } from './routes/_dashboard/jobs'
import { Route as DashboardAppRouteImport } from './routes/_dashboard/app'
import { Route as DashboardSessionsIndexRouteImport } from './routes/_dashboard/sessions/index'
import { Route as DashboardSessionsNewRouteImport } from './routes/_dashboard/sessions/new'
import { Route as DashboardSessionsSessionIdRouteImport } from './routes/_dashboard/sessions/$sessionId'

const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppRoute = DashboardAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsNewRoute = DashboardSessionsNewRouteImport.update({
  id: '/sessions/new',
  path: '/sessions/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsSessionIdRoute =
  DashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/site': typeof SiteRoute
  '/app': typeof DashboardAppRoute
  '/jobs': typeof DashboardJobsRoute
  '/profile': typeof DashboardProfileRoute
  '/resume': typeof DashboardResumeRoute
  '/settings': typeof DashboardSettingsRoute
  '/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/sessions/new': typeof DashboardSessionsNewRoute
  '/sessions/': typeof DashboardSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/site': typeof SiteRoute
  '/app': typeof DashboardAppRoute
  '/jobs': typeof DashboardJobsRoute
  '/profile': typeof DashboardProfileRoute
  '/resume': typeof DashboardResumeRoute
  '/settings': typeof DashboardSettingsRoute
  '/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/sessions/new': typeof DashboardSessionsNewRoute
  '/sessions': typeof DashboardSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/auth': typeof AuthRoute
  '/mission': typeof MissionRoute
  '/site': typeof SiteRoute
  '/_dashboard/app': typeof DashboardAppRoute
  '/_dashboard/jobs': typeof DashboardJobsRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/resume': typeof DashboardResumeRoute
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdRoute
  '/_dashboard/sessions/new': typeof DashboardSessionsNewRoute
  '/_dashboard/sessions/': typeof DashboardSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mission'
    | '/site'
    | '/app'
    | '/jobs'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mission'
    | '/site'
    | '/app'
    | '/jobs'
    | '/profile'
    | '/resume'
    | '/settings'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/auth'
    | '/mission'
    | '/site'
    | '/_dashboard/app'
    | '/_dashboard/jobs'
    | '/_dashboard/profile'
    | '/_dashboard/resume'
    | '/_dashboard/settings'
    | '/_dashboard/sessions/$sessionId'
    | '/_dashboard/sessions/new'
    | '/_dashboard/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthRoute: typeof AuthRoute
  MissionRoute: typeof MissionRoute
  SiteRoute: typeof SiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/resume': {
      id: '/_dashboard/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jobs': {
      id: '/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/app': {
      id: '/_dashboard/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof DashboardAppRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions/': {
      id: '/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof DashboardSessionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions/new': {
      id: '/_dashboard/sessions/new'
      path: '/sessions/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof DashboardSessionsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions/$sessionId': {
      id: '/_dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof DashboardSessionsSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAppRoute: typeof DashboardAppRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSessionsSessionIdRoute: typeof DashboardSessionsSessionIdRoute
  DashboardSessionsNewRoute: typeof DashboardSessionsNewRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppRoute: DashboardAppRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSessionsSessionIdRoute: DashboardSessionsSessionIdRoute,
  DashboardSessionsNewRoute: DashboardSessionsNewRoute,
  DashboardSessionsIndexRoute: DashboardSessionsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthRoute: AuthRoute,
  MissionRoute: MissionRoute,
  SiteRoute: SiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
