x-environment: &root-env
  REPO_ROOT: ${REPO_ROOT:-.} # default to current directory if not set externally
include:
  - path: ./infra/compose/base.yml
  - path: ./infra/compose/tts.yml
  - path: ./infra/compose/www.yml
