packages:
  - packages/ui/*
  - packages/tsconfig
  - packages/rollup-config
  - packages/utils
  - packages/mdx-generator
  - packages/types
  - packages/eslint
  - packages/maishatu-tw-eslint
  - packages/eslint-plugin-tailwindcss
