packages:
  - packages/ui/*
  - packages/browser-extensions/*
  - packages/tsconfig
  - packages/rollup-config
  - packages/utils
  - packages/mdx-generator
  - packages/types
  - packages/eslint
  - packages/maishatu-tw-eslint
  - packages/eslint-plugin-tailwindcss
  - crates/viewport-rotation
  - crates/some-crossword
  - crates/some-hexagon
