[package]
name = "pkg_cloner"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
dialoguer = { version = "0.12" }
serde_json = { workspace = true }

[dev-dependencies]
criterion = "0.8"
tempfile = "3.6"

[lints]
workspace = true

[[bench]]
name = "benchmark"
harness = false
