import { extensionConfig } from "@some-extension/common/vite"

// Platform split: content/background import `@censor/platform/*`, aliased to the
// Firefox or Chrome implementation per build target.
const platformAlias = (
  variant: "firefox" | "chrome"
): Record<string, string> => ({
  "@censor/platform/content": `src/lib/platform/content/api.${variant}.ts`,
  "@censor/platform/background": `src/lib/platform/background/api.${variant}.ts`,
  "@censor": "src",
})

// The diagnostics page (OBS2, #1396) is its own standalone extension page,
// reachable at its own moz-extension:// / chrome-extension:// URL, the way
// suspender-ledger's and some-filter's are. #1396 deliberately left the
// manifest's `default_popup` of "popup.html" unbuilt as a non-goal; "popup"
// below fills only that (the "Diagnostics" entry point), not the
// whitelist/enabled controls `@censor/types/messages` already models.
const entries = [
  { name: "content", input: "src/content/content.ts" },
  { name: "background", input: "src/background/background.ts" },
  { name: "debug", input: "debug.html", classic: false },
  { name: "popup", input: "popup.html", classic: false },
]

// The content stylesheet is a standalone file the manifest references
// (`"css": ["styles/content.css"]`), not a JS-injected style — so it is
// generated by the UnoCSS CLI rather than through Vite's CSS graph.
//
// `patterns` is ordered and the CLI concatenates raw `.css` inputs in list
// order ahead of the generated layers. veil-styles.ts comes first as the scan
// source; styles/content.css is both scanned and emitted, and lands above the
// utilities so the `!important` pre-mask occluder keeps winning while our own
// utilities still beat the tokens they read.
const unocss = [
  {
    config: "uno.config.ts",
    out: "dist/styles/content.css",
    preflights: false,
    patterns: ["src/lib/content/veil-styles.ts", "src/styles/content.css"],
  },
]

// One `vite build` per target. `--mode chromium` builds Chrome; the default
// (production) target is Firefox, matching the prior `build = build:firefox`.
// public/manifest.json is the chromium manifest (Vite's public-dir copy lands
// it at dist/manifest.json); the Firefox build overwrites it afterwards.
const config = ({
  mode,
}: {
  mode: string
}): ReturnType<typeof extensionConfig> => {
  const chromium = mode === "chromium"
  return extensionConfig({
    alias: platformAlias(chromium ? "chrome" : "firefox"),
    entries,
    unocss,
    copy: chromium
      ? []
      : [{ from: "public/manifest.firefox.json", to: "manifest.json" }],
  })
}

export default config
