#!/usr/bin/env node
// Extracts each composition's content from the Typst document and writes it as
// TypeScript for the web reading view (src/react).
//
// Why this exists. apps/www needs the résumé as *text*: a PDF does not render
// inline on mobile browsers, and Typst's SVG export contains no text at all —
// every glyph is a path — so neither can be read, selected, searched, or
// crawled on a phone. Before this, apps/www carried a hand-copied transcript
// of the résumé in TSX, which had already drifted from the source.
//
// So the text is derived instead. `typst query` reads the `<resume-export>`
// metadata that src/main.typ attaches to the document it just laid out, which
// means the web view and the PDF cannot describe different résumés.
//
// The output is committed rather than generated into dist/. It is small
// (~7 KB/variant), it makes content changes reviewable as a diff, and it keeps
// `tsc`, eslint, and knip working without depending on build order. `pnpm
// build` regenerates it first, so CI always renders from fresh data.
//
// The emitted file is annotated with the types in src/react/types.ts, so `tsc`
// checks the data against the declared shape. The assert below covers what
// types cannot: that a composition is not empty.
//
// This script is the one piece here that does not survive moving rendering to
// the server (paulgsc/some-ui#1132): once a service owns the résumé, it serves
// this payload directly and nothing queries `.typ` from Node. The *shape*
// below is the part that lasts — it becomes the response body.
import { execFileSync } from "node:child_process"
import { writeFileSync } from "node:fs"
import { join } from "node:path"

import {
  baseArgs,
  DEFAULT_TEMPLATE,
  inputArgs,
  packageDir,
  presentation,
  resolveTypst,
  sourceFile,
  variants,
} from "./typst.mjs"

const target = join(packageDir, "src", "react", "generated", "data.ts")

// A structural assert, not a schema. `tsc` already checks the emitted data
// against src/react/types.ts; this runs first and fails with a message that
// names the Typst file to fix, rather than a type error pointing into
// generated output.
const REQUIRED_KEYS = [
  "variant",
  "profile",
  "label",
  "summary",
  "skills",
  "projects",
  "platform",
  "highlights",
  "toolbox",
  "repositories",
  "engagement",
  "education",
  "languages",
  "certifications",
  "interests",
  "additionalExperience",
]
const REQUIRED_PROFILE_KEYS = ["name", "title", "email", "github", "portfolio"]
const NON_EMPTY_ARRAYS = ["projects", "platform", "highlights", "toolbox"]

function assertShape(variant, data) {
  const missing = REQUIRED_KEYS.filter((key) => !(key in data))
  if (missing.length) {
    throw new Error(
      `${variant}: <resume-export> is missing ${missing.join(", ")}. ` +
        `Update the metadata block in src/main.typ.`
    )
  }
  const missingProfile = REQUIRED_PROFILE_KEYS.filter(
    (key) => typeof data.profile?.[key] !== "string"
  )
  if (missingProfile.length) {
    throw new Error(
      `${variant}: profile is missing string ${missingProfile.join(", ")}.`
    )
  }
  for (const key of NON_EMPTY_ARRAYS) {
    if (!Array.isArray(data[key]) || data[key].length === 0) {
      throw new Error(
        `${variant}: expected a non-empty array for "${key}". A composition ` +
          `that renders nothing here would publish a blank section.`
      )
    }
  }
}

async function main() {
  const { bin, fontPath } = await resolveTypst()

  const exported = {}
  for (const variant of variants) {
    const json = execFileSync(
      bin,
      [
        "query",
        sourceFile,
        "<resume-export>",
        "--field",
        "value",
        "--one",
        "--format",
        "json",
        ...baseArgs(fontPath),
        ...inputArgs({
          variant,
          template: DEFAULT_TEMPLATE,
          ...presentation[DEFAULT_TEMPLATE],
        }),
      ],
      { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 }
    )
    const data = JSON.parse(json)
    assertShape(variant, data)
    exported[variant] = data
    // eslint-disable-next-line no-console
    console.log(
      `[resume] exported ${variant}: ${data.projects.length} projects, ` +
        `${data.highlights.length} highlights`
    )
  }

  const banner = `// GENERATED by scripts/export-data.mjs — do not edit.
//
// Source of truth is src/data/resume.typ (content) and src/data/personal.typ
// (facts that cannot be derived from the source repositories). Run
// \`pnpm --filter @some-ui/resume export:data\` after changing either.

import type { ResumeData, ResumeVariant } from "@resume/types"

`
  writeFileSync(
    target,
    `${banner}export const resumeData: Record<ResumeVariant, ResumeData> = ` +
      `${JSON.stringify(exported, null, 2)}\n`
  )
  // eslint-disable-next-line no-console
  console.log(`[resume] wrote ${target}`)
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(`[resume] ${err.message}`)
  process.exitCode = 1
})
