[package]
name = "some-fsm-input"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.5", features = ["csr"] }
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "Document", 
        "Element", 
        "HtmlElement",
        "HtmlFormElement",
        "Window", 
        "EventTarget",
        "KeyboardEvent",
        "MouseEvent", 
        "Event",
        "Node",
        "console"
]}
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
console_error_panic_hook = "0.1"

[lints]
workspace = true
