[package]
name = "viewport-rotation"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true
description = "WebAssembly utilities for tracking and transforming viewport rotation."
readme = "README.md"
keywords = ["rotation", "viewport", "wasm"]
categories = ["graphics", "wasm"]


[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.6"

[dev-dependencies]
wasm-bindgen-test = "0.3"
console_error_panic_hook = "0.1"

[lints]
workspace = true
