/**
 * The bundled read-aloud deck: what the drill reads when no other deck has
 * been loaded, and what it falls back to when one fails to parse (canon
 * Thm. 8.2).
 *
 * Hand-checked, like `@some-ui/honeycomb`'s demo seed. Six café lines at
 * level 1 (the handheld fixture's scene), then two lines per level of
 * everyday sentences, so a set can mix short and long reads from the start
 * (canon Rem. 4.9). Pronunciations are given only where they differ from the
 * spelling, and each follows a standard rule: liaison (주말에 → 주마레),
 * nasalisation (합니다 → 함니다), tensing (식당 → 식땅, 볼 거 → 볼 꺼),
 * palatalisation (같이 → 가치), a silent ㅎ (많아요 → 마나요), and 져 said as
 * 저 (추워져서 → 추워저서). A syllable where stem and ending merge counts as
 * stem (마셔요 is 마셔 + 요). Its test parses it with no findings.
 */

import type { ReadAloudDeck } from "@topik/lib/topik/read-aloud/content"

export const STARTER_DECK: ReadAloudDeck = {
  id: "starter",
  title: "Read-aloud starter",
  words: [
    { id: "eoseo", lemma: "어서", gloss: "quickly; come on in" },
    { id: "oda", lemma: "오다", gloss: "come" },
    { id: "mwo", lemma: "뭐", gloss: "what" },
    { id: "deurida", lemma: "드리다", gloss: "give (humble)" },
    { id: "aiseu", lemma: "아이스", gloss: "iced" },
    { id: "amerikano", lemma: "아메리카노", gloss: "americano" },
    { id: "hana", lemma: "하나", gloss: "one" },
    { id: "jan", lemma: "잔", gloss: "cup (counter for drinks)" },
    { id: "juda", lemma: "주다", gloss: "give" },
    { id: "yeogi", lemma: "여기", gloss: "here" },
    { id: "deusida", lemma: "드시다", gloss: "eat, drink (honorific)" },
    { id: "gada", lemma: "가다", gloss: "go" },
    { id: "aniyo", lemma: "아니요", gloss: "no" },
    { id: "pojanghada", lemma: "포장하다", gloss: "wrap; get to go" },
    {
      id: "sacheon-obaek",
      lemma: "사천오백",
      gloss: "four thousand five hundred",
    },
    { id: "won", lemma: "원", gloss: "won (currency)" },
    { id: "kadeu", lemma: "카드", gloss: "card" },
    { id: "hada", lemma: "하다", gloss: "do" },
    { id: "gamsahada", lemma: "감사하다", gloss: "be thankful" },
    { id: "jeo", lemma: "저", gloss: "I (humble)" },
    { id: "achim", lemma: "아침", gloss: "morning" },
    { id: "keopi", lemma: "커피", gloss: "coffee" },
    { id: "masida", lemma: "마시다", gloss: "drink" },
    { id: "jumal", lemma: "주말", gloss: "weekend" },
    { id: "chingu", lemma: "친구", gloss: "friend" },
    { id: "gachi", lemma: "같이", gloss: "together" },
    { id: "sijang", lemma: "시장", gloss: "market" },
    { id: "gwail", lemma: "과일", gloss: "fruit" },
    { id: "sada", lemma: "사다", gloss: "buy" },
    { id: "bi", lemma: "비", gloss: "rain" },
    { id: "oneul", lemma: "오늘", gloss: "today" },
    { id: "jip", lemma: "집", gloss: "home, house" },
    { id: "yeonghwa", lemma: "영화", gloss: "movie" },
    { id: "boda", lemma: "보다", gloss: "see, watch" },
    { id: "geot", lemma: "것", gloss: "thing" },
    { id: "yojeum", lemma: "요즘", gloss: "these days" },
    { id: "nalssi", lemma: "날씨", gloss: "weather" },
    { id: "chuwojida", lemma: "추워지다", gloss: "get cold" },
    { id: "ttatteuthada", lemma: "따뜻하다", gloss: "be warm" },
    { id: "ot", lemma: "옷", gloss: "clothes" },
    { id: "ipda", lemma: "입다", gloss: "wear (clothes)" },
    { id: "danida", lemma: "다니다", gloss: "go around, attend" },
    { id: "saram", lemma: "사람", gloss: "person" },
    { id: "manhajida", lemma: "많아지다", gloss: "become many" },
    { id: "hoesa", lemma: "회사", gloss: "company, office" },
    { id: "geuncheo", lemma: "근처", gloss: "vicinity" },
    { id: "saero", lemma: "새로", gloss: "newly" },
    { id: "saenggida", lemma: "생기다", gloss: "come into being, open" },
    { id: "sikdang", lemma: "식당", gloss: "restaurant" },
    { id: "eumsik", lemma: "음식", gloss: "food" },
    { id: "masitda", lemma: "맛있다", gloss: "be tasty" },
    { id: "gagyeok", lemma: "가격", gloss: "price" },
    { id: "ssada", lemma: "싸다", gloss: "be cheap" },
    { id: "jeomsim-sigan", lemma: "점심시간", gloss: "lunchtime" },
    { id: "manta", lemma: "많다", gloss: "be many, a lot" },
  ],
  lines: [
    {
      id: "cafe-welcome",
      level: 1,
      korean: "어서 오세요. 뭐 드릴까요?",
      english: "Welcome. What can I get you?",
      words: [
        { wordId: "eoseo", surface: "어서", stemEnd: 2 },
        {
          wordId: "oda",
          surface: "오세요",
          stemEnd: 1,
          sense: "please come (polite)",
        },
        { wordId: "mwo", surface: "뭐", stemEnd: 1 },
        {
          wordId: "deurida",
          surface: "드릴까요",
          stemEnd: 2,
          sense: "shall I give you? (humble)",
        },
      ],
    },
    {
      id: "cafe-order",
      level: 1,
      korean: "아이스 아메리카노 한 잔 주세요.",
      english: "One iced americano, please.",
      words: [
        { wordId: "aiseu", surface: "아이스", stemEnd: 3 },
        { wordId: "amerikano", surface: "아메리카노", stemEnd: 5 },
        {
          wordId: "hana",
          surface: "한",
          stemEnd: 1,
          sense: "one (before a counter)",
        },
        { wordId: "jan", surface: "잔", stemEnd: 1 },
        {
          wordId: "juda",
          surface: "주세요",
          stemEnd: 1,
          sense: "please give me",
        },
      ],
    },
    {
      id: "cafe-for-here",
      level: 1,
      korean: "여기서 드시고 가세요?",
      english: "Is that for here?",
      words: [
        {
          wordId: "yeogi",
          surface: "여기서",
          stemEnd: 2,
          sense: "here (at this place)",
        },
        {
          wordId: "deusida",
          surface: "드시고",
          stemEnd: 2,
          sense: "eat, and then",
        },
        { wordId: "gada", surface: "가세요", stemEnd: 1, sense: "go (polite)" },
      ],
    },
    {
      id: "cafe-to-go",
      level: 1,
      korean: "아니요, 포장해 주세요.",
      english: "No, to go please.",
      words: [
        { wordId: "aniyo", surface: "아니요", stemEnd: 3 },
        {
          wordId: "pojanghada",
          surface: "포장해",
          stemEnd: 3,
          sense: "wrap it (up)",
        },
        {
          wordId: "juda",
          surface: "주세요",
          stemEnd: 1,
          sense: "please (do it for me)",
        },
      ],
    },
    {
      id: "cafe-price",
      level: 1,
      korean: "사천오백 원입니다.",
      english: "That's 4,500 won.",
      words: [
        {
          wordId: "sacheon-obaek",
          surface: "사천오백",
          stemEnd: 4,
          pronunciation: "사처노백",
        },
        {
          wordId: "won",
          surface: "원입니다",
          stemEnd: 1,
          pronunciation: "워님니다",
          sense: "it's … won",
        },
      ],
    },
    {
      id: "cafe-pay",
      level: 1,
      korean: "카드로 할게요. 감사합니다.",
      english: "I'll pay by card. Thank you.",
      words: [
        { wordId: "kadeu", surface: "카드로", stemEnd: 2, sense: "by card" },
        {
          wordId: "hada",
          surface: "할게요",
          stemEnd: 1,
          pronunciation: "할께요",
          sense: "I'll do (it)",
        },
        {
          wordId: "gamsahada",
          surface: "감사합니다",
          stemEnd: 3,
          pronunciation: "감사함니다",
          sense: "thank you",
        },
      ],
    },
    {
      id: "morning-coffee",
      level: 1,
      korean: "저는 아침마다 커피를 한 잔 마셔요.",
      english: "I drink a cup of coffee every morning.",
      words: [
        { wordId: "jeo", surface: "저는", stemEnd: 1 },
        {
          wordId: "achim",
          surface: "아침마다",
          stemEnd: 2,
          sense: "every morning",
        },
        { wordId: "keopi", surface: "커피를", stemEnd: 2 },
        {
          wordId: "hana",
          surface: "한",
          stemEnd: 1,
          sense: "one (before a counter)",
        },
        { wordId: "jan", surface: "잔", stemEnd: 1 },
        {
          wordId: "masida",
          surface: "마셔요",
          stemEnd: 2,
          sense: "drink (polite)",
        },
      ],
    },
    {
      id: "weekend-market",
      level: 2,
      korean: "주말에 친구하고 같이 시장에 가서 과일을 샀어요.",
      english:
        "At the weekend I went to the market with a friend and bought fruit.",
      words: [
        {
          wordId: "jumal",
          surface: "주말에",
          stemEnd: 2,
          pronunciation: "주마레",
          sense: "at the weekend",
        },
        {
          wordId: "chingu",
          surface: "친구하고",
          stemEnd: 2,
          sense: "with a friend",
        },
        { wordId: "gachi", surface: "같이", stemEnd: 2, pronunciation: "가치" },
        {
          wordId: "sijang",
          surface: "시장에",
          stemEnd: 2,
          sense: "to the market",
        },
        { wordId: "gada", surface: "가서", stemEnd: 1, sense: "go, and then" },
        {
          wordId: "gwail",
          surface: "과일을",
          stemEnd: 2,
          pronunciation: "과이를",
        },
        {
          wordId: "sada",
          surface: "샀어요",
          stemEnd: 1,
          pronunciation: "사써요",
          sense: "bought",
        },
      ],
    },
    {
      id: "rainy-movie",
      level: 2,
      korean: "비가 와서 오늘은 집에서 영화를 볼 거예요.",
      english: "It's raining, so today I'm going to watch a movie at home.",
      words: [
        { wordId: "bi", surface: "비가", stemEnd: 1 },
        {
          wordId: "oda",
          surface: "와서",
          stemEnd: 1,
          sense: "comes (of rain: falls), so",
        },
        {
          wordId: "oneul",
          surface: "오늘은",
          stemEnd: 2,
          pronunciation: "오느른",
        },
        {
          wordId: "jip",
          surface: "집에서",
          stemEnd: 1,
          pronunciation: "지베서",
          sense: "at home",
        },
        { wordId: "yeonghwa", surface: "영화를", stemEnd: 2 },
        { wordId: "boda", surface: "볼", stemEnd: 1, sense: "watch (future)" },
        {
          wordId: "geot",
          surface: "거예요",
          stemEnd: 1,
          pronunciation: "꺼예요",
          sense: "(-ㄹ 거예요) will",
        },
      ],
    },
    {
      id: "cold-weather",
      level: 3,
      korean: "요즘 날씨가 추워져서 따뜻한 옷을 입고 다니는 사람이 많아졌어요.",
      english:
        "It's got cold lately, so more people are going around in warm clothes.",
      words: [
        { wordId: "yojeum", surface: "요즘", stemEnd: 2 },
        { wordId: "nalssi", surface: "날씨가", stemEnd: 2 },
        {
          wordId: "chuwojida",
          surface: "추워져서",
          stemEnd: 3,
          pronunciation: "추워저서",
          sense: "has got cold, so",
        },
        {
          wordId: "ttatteuthada",
          surface: "따뜻한",
          stemEnd: 3,
          pronunciation: "따뜨탄",
          sense: "warm (describing a noun)",
        },
        { wordId: "ot", surface: "옷을", stemEnd: 1, pronunciation: "오슬" },
        {
          wordId: "ipda",
          surface: "입고",
          stemEnd: 1,
          pronunciation: "입꼬",
          sense: "wear, and",
        },
        {
          wordId: "danida",
          surface: "다니는",
          stemEnd: 2,
          sense: "going around (describing a noun)",
        },
        {
          wordId: "saram",
          surface: "사람이",
          stemEnd: 2,
          pronunciation: "사라미",
        },
        {
          wordId: "manhajida",
          surface: "많아졌어요",
          stemEnd: 3,
          pronunciation: "마나저써요",
          sense: "have become many",
        },
      ],
    },
    {
      id: "new-restaurant",
      level: 3,
      korean:
        "회사 근처에 새로 생긴 식당은 음식이 맛있고 가격도 싸서 점심시간마다 사람이 많아요.",
      english:
        "The new place near the office has good food and low prices, so it's busy every lunchtime.",
      words: [
        { wordId: "hoesa", surface: "회사", stemEnd: 2 },
        { wordId: "geuncheo", surface: "근처에", stemEnd: 2, sense: "near" },
        { wordId: "saero", surface: "새로", stemEnd: 2 },
        {
          wordId: "saenggida",
          surface: "생긴",
          stemEnd: 2,
          sense: "that opened",
        },
        {
          wordId: "sikdang",
          surface: "식당은",
          stemEnd: 2,
          pronunciation: "식땅은",
        },
        {
          wordId: "eumsik",
          surface: "음식이",
          stemEnd: 2,
          pronunciation: "음시기",
        },
        {
          wordId: "masitda",
          surface: "맛있고",
          stemEnd: 2,
          pronunciation: "마싣꼬",
          sense: "tasty, and",
        },
        {
          wordId: "gagyeok",
          surface: "가격도",
          stemEnd: 2,
          pronunciation: "가격또",
          sense: "the price, too",
        },
        { wordId: "ssada", surface: "싸서", stemEnd: 1, sense: "cheap, so" },
        {
          wordId: "jeomsim-sigan",
          surface: "점심시간마다",
          stemEnd: 4,
          pronunciation: "점심씨간마다",
          sense: "every lunchtime",
        },
        {
          wordId: "saram",
          surface: "사람이",
          stemEnd: 2,
          pronunciation: "사라미",
        },
        {
          wordId: "manta",
          surface: "많아요",
          stemEnd: 1,
          pronunciation: "마나요",
          sense: "there are many",
        },
      ],
    },
  ],
}
