
[target.'cfg(all())']
rustflags = [
"-W", "clippy::all",
"-W", "clippy::pedantic",
"-W", "clippy::nursery",
"-W", "clippy::cargo",
"-D", "clippy::unwrap_used",
"-W", "clippy::expect_used",
"-W", "clippy::perf",
"-W", "clippy::style",
"-W", "clippy::complexity",
"-D", "clippy::suspicious",
"-W", "clippy::doc_markdown",
"-A", "clippy::missing_docs_in_private_items",
"-A", "clippy::module_name_repetitions",
"-D", "warnings"
]

[alias]
wasm = "run -- wasm-pack build --target web --out-dir dist"

