/**
 * Level-one read-aloud lines: everyday beginner sentences, written to cover
 * the beginner vocabulary a TOPIK I reader meets first (adaptive-learning
 * canon Def. 4.8, Cor. 4.6).
 *
 * Source: the words were chosen by hand as common beginner vocabulary. The
 * intended reference, the National Institute of Korean Language's graded
 * learner list (한국어 학습용 어휘 목록, grade A), could not be fetched when
 * this was written, so these are not checked against it; aligning them is
 * follow-up work.
 *
 * Hand-checked like the starter deck, under the same conventions: every run
 * of Hangul is one occurrence, a syllable where stem and ending merge counts
 * as stem (마셔요 is 마셔 + 요), and a pronunciation is given only where it
 * differs from the spelling, within the written word, by a standard rule:
 * liaison (책을 → 채글), tensing (학교에 → 학꾜에, 먹기 → 먹끼),
 * aspiration (백화점에서 → 배콰저메서) and a silent ㅎ (좋아요 → 조아요).
 * Changes across a space are not written. Words the starter deck
 * already names (저, 친구, 마시다 …) are named there, not here; the bundled
 * deck joins the two.
 */

import type {
  ReadAloudLine,
  ReadAloudWord,
} from "@topik/lib/topik/read-aloud/content"

export const LEVEL_ONE_WORDS: Array<ReadAloudWord> = [
  { id: "annyeonghada", lemma: "안녕하다", gloss: "be well" },
  { id: "haksaeng", lemma: "학생", gloss: "student" },
  { id: "ireum", lemma: "이름", gloss: "name" },
  { id: "miguk", lemma: "미국", gloss: "America" },
  { id: "hangugeo", lemma: "한국어", gloss: "Korean (language)" },
  { id: "gongbuhada", lemma: "공부하다", gloss: "study" },
  { id: "uri", lemma: "우리", gloss: "we, our" },
  { id: "gajok", lemma: "가족", gloss: "family" },
  { id: "net", lemma: "넷", gloss: "four" },
  { id: "myeong", lemma: "명", gloss: "counter for people" },
  { id: "abeoji", lemma: "아버지", gloss: "father" },
  { id: "eomeoni", lemma: "어머니", gloss: "mother" },
  { id: "itda", lemma: "있다", gloss: "be there, have" },
  { id: "hyeong", lemma: "형", gloss: "older brother (of a man)" },
  { id: "ki", lemma: "키", gloss: "height" },
  { id: "keuda", lemma: "크다", gloss: "be big, be tall" },
  { id: "ilgop", lemma: "일곱", gloss: "seven" },
  { id: "si", lemma: "시", gloss: "o'clock" },
  { id: "ireonada", lemma: "일어나다", gloss: "get up" },
  { id: "ppang", lemma: "빵", gloss: "bread" },
  { id: "meokda", lemma: "먹다", gloss: "eat" },
  { id: "mul", lemma: "물", gloss: "water" },
  { id: "mani", lemma: "많이", gloss: "a lot" },
  { id: "hakgyo", lemma: "학교", gloss: "school" },
  { id: "beoseu", lemma: "버스", gloss: "bus" },
  { id: "seonsaengnim", lemma: "선생님", gloss: "teacher" },
  { id: "chinjeolhada", lemma: "친절하다", gloss: "be kind" },
  { id: "gyosil", lemma: "교실", gloss: "classroom" },
  { id: "chaek", lemma: "책", gloss: "book" },
  { id: "jeonyeok", lemma: "저녁", gloss: "evening" },
  { id: "sukje", lemma: "숙제", gloss: "homework" },
  { id: "doseogwan", lemma: "도서관", gloss: "library" },
  { id: "ikda", lemma: "읽다", gloss: "read" },
  { id: "jeomsim", lemma: "점심", gloss: "lunch" },
  { id: "gimchi", lemma: "김치", gloss: "kimchi" },
  { id: "jogeum", lemma: "조금", gloss: "a little" },
  { id: "maepda", lemma: "맵다", gloss: "be spicy" },
  { id: "sagwa", lemma: "사과", gloss: "apple" },
  { id: "eolma", lemma: "얼마", gloss: "how much" },
  { id: "gage", lemma: "가게", gloss: "shop" },
  { id: "uyu", lemma: "우유", gloss: "milk" },
  { id: "jota", lemma: "좋다", gloss: "be good" },
  { id: "usan", lemma: "우산", gloss: "umbrella" },
  { id: "sseuda", lemma: "쓰다", gloss: "use; write" },
  { id: "gyeoul", lemma: "겨울", gloss: "winter" },
  { id: "chupda", lemma: "춥다", gloss: "be cold" },
  { id: "yeoreum", lemma: "여름", gloss: "summer" },
  { id: "bada", lemma: "바다", gloss: "sea" },
  { id: "swida", lemma: "쉬다", gloss: "rest" },
  { id: "iryoil", lemma: "일요일", gloss: "Sunday" },
  { id: "gongwon", lemma: "공원", gloss: "park" },
  { id: "undonghada", lemma: "운동하다", gloss: "exercise" },
  { id: "meori", lemma: "머리", gloss: "head" },
  { id: "apeuda", lemma: "아프다", gloss: "hurt, be sick" },
  { id: "byeongwon", lemma: "병원", gloss: "hospital" },
  { id: "yakguk", lemma: "약국", gloss: "pharmacy" },
  { id: "eodi", lemma: "어디", gloss: "where" },
  { id: "eunhaeng", lemma: "은행", gloss: "bank" },
  { id: "ucheguk", lemma: "우체국", gloss: "post office" },
  { id: "yeop", lemma: "옆", gloss: "side" },
  { id: "yeok", lemma: "역", gloss: "station" },
  { id: "geotda", lemma: "걷다", gloss: "walk" },
  { id: "jigeum", lemma: "지금", gloss: "now" },
  { id: "myeot", lemma: "몇", gloss: "how many, what (number)" },
  { id: "baekhwajeom", lemma: "백화점", gloss: "department store" },
  { id: "i", lemma: "이", gloss: "this" },
  { id: "sinbal", lemma: "신발", gloss: "shoes" },
  { id: "neomu", lemma: "너무", gloss: "too" },
  { id: "jakda", lemma: "작다", gloss: "be small" },
  { id: "jeonhwahada", lemma: "전화하다", gloss: "phone, call" },
  { id: "joahada", lemma: "좋아하다", gloss: "like" },
  { id: "cha", lemma: "차", gloss: "tea" },
  { id: "an", lemma: "안", gloss: "not" },
  { id: "gangaji", lemma: "강아지", gloss: "puppy" },
  { id: "jeongmal", lemma: "정말", gloss: "really" },
  { id: "gwiyeopda", lemma: "귀엽다", gloss: "be cute" },
  { id: "goyangi", lemma: "고양이", gloss: "cat" },
  { id: "sopa", lemma: "소파", gloss: "sofa" },
  { id: "jada", lemma: "자다", gloss: "sleep" },
  { id: "pigonhada", lemma: "피곤하다", gloss: "be tired" },
  { id: "iljjik", lemma: "일찍", gloss: "early" },
  { id: "maeil", lemma: "매일", gloss: "every day" },
  { id: "eumak", lemma: "음악", gloss: "music" },
  { id: "deutda", lemma: "듣다", gloss: "listen" },
  { id: "sajin", lemma: "사진", gloss: "photo" },
  { id: "jjikda", lemma: "찍다", gloss: "take (a photo)" },
  { id: "dongsaeng", lemma: "동생", gloss: "younger sibling" },
  { id: "godeunghaksaeng", lemma: "고등학생", gloss: "high school student" },
  { id: "je", lemma: "제", gloss: "my (humble)" },
  { id: "saengil", lemma: "생일", gloss: "birthday" },
  { id: "gwaenchanta", lemma: "괜찮다", gloss: "be okay" },
  { id: "cheonmaneyo", lemma: "천만에요", gloss: "you're welcome" },
  { id: "neutda", lemma: "늦다", gloss: "be late" },
  { id: "mianhada", lemma: "미안하다", gloss: "be sorry" },
  { id: "woryoil", lemma: "월요일", gloss: "Monday" },
  { id: "geumyoil", lemma: "금요일", gloss: "Friday" },
  { id: "ilhada", lemma: "일하다", gloss: "work" },
  { id: "hanguk", lemma: "한국", gloss: "Korea" },
  { id: "bae", lemma: "배", gloss: "stomach" },
  { id: "gopeuda", lemma: "고프다", gloss: "be hungry" },
  { id: "mok", lemma: "목", gloss: "throat" },
  { id: "mareuda", lemma: "마르다", gloss: "be dry" },
  { id: "anta", lemma: "않다", gloss: "not (do or be)" },
  { id: "bang", lemma: "방", gloss: "room" },
  { id: "cheongsohada", lemma: "청소하다", gloss: "clean" },
  { id: "changmun", lemma: "창문", gloss: "window" },
  { id: "yeolda", lemma: "열다", gloss: "open" },
  { id: "mun", lemma: "문", gloss: "door" },
  { id: "datda", lemma: "닫다", gloss: "close, shut" },
  { id: "bap", lemma: "밥", gloss: "rice, a meal" },
  { id: "jeon", lemma: "전", gloss: "before" },
  { id: "son", lemma: "손", gloss: "hand" },
  { id: "ssitda", lemma: "씻다", gloss: "wash" },
  { id: "anda", lemma: "앉다", gloss: "sit" },
  { id: "syawo", lemma: "샤워", gloss: "shower" },
  { id: "eoryeopda", lemma: "어렵다", gloss: "be difficult" },
  { id: "naeil", lemma: "내일", gloss: "tomorrow" },
  { id: "mannada", lemma: "만나다", gloss: "meet" },
  { id: "eoje", lemma: "어제", gloss: "yesterday" },
  { id: "bappeuda", lemma: "바쁘다", gloss: "be busy" },
  { id: "sae", lemma: "새", gloss: "new" },
  { id: "jadongcha", lemma: "자동차", gloss: "car" },
  { id: "pyeonji", lemma: "편지", gloss: "letter" },
]

export const LEVEL_ONE_LINES: Array<ReadAloudLine> = [
  {
    id: "intro-student",
    level: 1,
    korean: "안녕하세요. 저는 학생이에요.",
    english: "Hello. I'm a student.",
    words: [
      {
        wordId: "annyeonghada",
        surface: "안녕하세요",
        stemEnd: 3,
        sense: "hello (polite)",
      },
      { wordId: "jeo", surface: "저는", stemEnd: 1 },
      {
        wordId: "haksaeng",
        surface: "학생이에요",
        stemEnd: 2,
        pronunciation: "학쌩이에요",
        sense: "am a student",
      },
    ],
  },
  {
    id: "intro-name",
    level: 1,
    korean: "이름이 뭐예요?",
    english: "What's your name?",
    words: [
      {
        wordId: "ireum",
        surface: "이름이",
        stemEnd: 2,
        pronunciation: "이르미",
      },
      { wordId: "mwo", surface: "뭐예요", stemEnd: 1, sense: "what is it?" },
    ],
  },
  {
    id: "intro-country",
    level: 1,
    korean: "저는 미국 사람이에요.",
    english: "I'm American.",
    words: [
      { wordId: "jeo", surface: "저는", stemEnd: 1 },
      { wordId: "miguk", surface: "미국", stemEnd: 2 },
      {
        wordId: "saram",
        surface: "사람이에요",
        stemEnd: 2,
        pronunciation: "사라미에요",
        sense: "am a person",
      },
    ],
  },
  {
    id: "study-korean",
    level: 1,
    korean: "한국어를 공부해요.",
    english: "I study Korean.",
    words: [
      {
        wordId: "hangugeo",
        surface: "한국어를",
        stemEnd: 3,
        pronunciation: "한구거를",
      },
      { wordId: "gongbuhada", surface: "공부해요", stemEnd: 3 },
    ],
  },
  {
    id: "family-four",
    level: 1,
    korean: "우리 가족은 네 명이에요.",
    english: "There are four of us in my family.",
    words: [
      { wordId: "uri", surface: "우리", stemEnd: 2 },
      {
        wordId: "gajok",
        surface: "가족은",
        stemEnd: 2,
        pronunciation: "가조근",
      },
      {
        wordId: "net",
        surface: "네",
        stemEnd: 1,
        sense: "four (before a counter)",
      },
      {
        wordId: "myeong",
        surface: "명이에요",
        stemEnd: 1,
        sense: "is (so many) people",
      },
    ],
  },
  {
    id: "family-parents",
    level: 1,
    korean: "아버지와 어머니가 있어요.",
    english: "I have a father and a mother.",
    words: [
      { wordId: "abeoji", surface: "아버지와", stemEnd: 3 },
      { wordId: "eomeoni", surface: "어머니가", stemEnd: 3 },
      {
        wordId: "itda",
        surface: "있어요",
        stemEnd: 1,
        pronunciation: "이써요",
        sense: "there is, I have",
      },
    ],
  },
  {
    id: "brother-tall",
    level: 1,
    korean: "형은 키가 커요.",
    english: "My older brother is tall.",
    words: [
      { wordId: "hyeong", surface: "형은", stemEnd: 1 },
      { wordId: "ki", surface: "키가", stemEnd: 1 },
      { wordId: "keuda", surface: "커요", stemEnd: 1, sense: "is tall" },
    ],
  },
  {
    id: "morning-wake",
    level: 1,
    korean: "아침 일곱 시에 일어나요.",
    english: "I get up at seven in the morning.",
    words: [
      { wordId: "achim", surface: "아침", stemEnd: 2 },
      { wordId: "ilgop", surface: "일곱", stemEnd: 2 },
      { wordId: "si", surface: "시에", stemEnd: 1 },
      {
        wordId: "ireonada",
        surface: "일어나요",
        stemEnd: 3,
        pronunciation: "이러나요",
      },
    ],
  },
  {
    id: "breakfast-bread",
    level: 1,
    korean: "아침에 빵을 먹어요.",
    english: "I eat bread in the morning.",
    words: [
      {
        wordId: "achim",
        surface: "아침에",
        stemEnd: 2,
        pronunciation: "아치메",
      },
      { wordId: "ppang", surface: "빵을", stemEnd: 1 },
      {
        wordId: "meokda",
        surface: "먹어요",
        stemEnd: 1,
        pronunciation: "머거요",
      },
    ],
  },
  {
    id: "water-lots",
    level: 1,
    korean: "물을 많이 마셔요.",
    english: "I drink a lot of water.",
    words: [
      { wordId: "mul", surface: "물을", stemEnd: 1, pronunciation: "무를" },
      { wordId: "mani", surface: "많이", stemEnd: 2, pronunciation: "마니" },
      { wordId: "masida", surface: "마셔요", stemEnd: 2 },
    ],
  },
  {
    id: "school-bus",
    level: 1,
    korean: "학교에 버스로 가요.",
    english: "I go to school by bus.",
    words: [
      {
        wordId: "hakgyo",
        surface: "학교에",
        stemEnd: 2,
        pronunciation: "학꾜에",
      },
      { wordId: "beoseu", surface: "버스로", stemEnd: 2, sense: "by bus" },
      { wordId: "gada", surface: "가요", stemEnd: 1 },
    ],
  },
  {
    id: "teacher-kind",
    level: 1,
    korean: "선생님이 친절해요.",
    english: "The teacher is kind.",
    words: [
      {
        wordId: "seonsaengnim",
        surface: "선생님이",
        stemEnd: 3,
        pronunciation: "선생니미",
      },
      { wordId: "chinjeolhada", surface: "친절해요", stemEnd: 3 },
    ],
  },
  {
    id: "classroom-books",
    level: 1,
    korean: "교실에 책이 많아요.",
    english: "There are a lot of books in the classroom.",
    words: [
      {
        wordId: "gyosil",
        surface: "교실에",
        stemEnd: 2,
        pronunciation: "교시레",
      },
      { wordId: "chaek", surface: "책이", stemEnd: 1, pronunciation: "채기" },
      {
        wordId: "manta",
        surface: "많아요",
        stemEnd: 1,
        pronunciation: "마나요",
      },
    ],
  },
  {
    id: "evening-homework",
    level: 1,
    korean: "저녁에 숙제를 해요.",
    english: "I do my homework in the evening.",
    words: [
      {
        wordId: "jeonyeok",
        surface: "저녁에",
        stemEnd: 2,
        pronunciation: "저녀게",
      },
      {
        wordId: "sukje",
        surface: "숙제를",
        stemEnd: 2,
        pronunciation: "숙쩨를",
      },
      { wordId: "hada", surface: "해요", stemEnd: 1 },
    ],
  },
  {
    id: "library-read",
    level: 1,
    korean: "도서관에서 책을 읽어요.",
    english: "I read books at the library.",
    words: [
      {
        wordId: "doseogwan",
        surface: "도서관에서",
        stemEnd: 3,
        pronunciation: "도서과네서",
      },
      { wordId: "chaek", surface: "책을", stemEnd: 1, pronunciation: "채글" },
      {
        wordId: "ikda",
        surface: "읽어요",
        stemEnd: 1,
        pronunciation: "일거요",
      },
    ],
  },
  {
    id: "lunch-friend",
    level: 1,
    korean: "친구와 점심을 먹어요.",
    english: "I have lunch with a friend.",
    words: [
      { wordId: "chingu", surface: "친구와", stemEnd: 2 },
      {
        wordId: "jeomsim",
        surface: "점심을",
        stemEnd: 2,
        pronunciation: "점시믈",
      },
      {
        wordId: "meokda",
        surface: "먹어요",
        stemEnd: 1,
        pronunciation: "머거요",
      },
    ],
  },
  {
    id: "kimchi-spicy",
    level: 1,
    korean: "김치가 조금 매워요.",
    english: "The kimchi is a little spicy.",
    words: [
      { wordId: "gimchi", surface: "김치가", stemEnd: 2 },
      { wordId: "jogeum", surface: "조금", stemEnd: 2 },
      { wordId: "maepda", surface: "매워요", stemEnd: 2, sense: "is spicy" },
    ],
  },
  {
    id: "apple-price",
    level: 1,
    korean: "사과가 얼마예요?",
    english: "How much are the apples?",
    words: [
      { wordId: "sagwa", surface: "사과가", stemEnd: 2 },
      {
        wordId: "eolma",
        surface: "얼마예요",
        stemEnd: 2,
        sense: "how much is it?",
      },
    ],
  },
  {
    id: "shop-milk",
    level: 1,
    korean: "가게에서 우유를 사요.",
    english: "I buy milk at the shop.",
    words: [
      { wordId: "gage", surface: "가게에서", stemEnd: 2 },
      { wordId: "uyu", surface: "우유를", stemEnd: 2 },
      { wordId: "sada", surface: "사요", stemEnd: 1 },
    ],
  },
  {
    id: "weather-nice",
    level: 1,
    korean: "오늘 날씨가 좋아요.",
    english: "The weather is nice today.",
    words: [
      { wordId: "oneul", surface: "오늘", stemEnd: 2 },
      { wordId: "nalssi", surface: "날씨가", stemEnd: 2 },
      {
        wordId: "jota",
        surface: "좋아요",
        stemEnd: 1,
        pronunciation: "조아요",
      },
    ],
  },
  {
    id: "rain-umbrella",
    level: 1,
    korean: "비가 와서 우산을 써요.",
    english: "It's raining, so I use an umbrella.",
    words: [
      { wordId: "bi", surface: "비가", stemEnd: 1 },
      { wordId: "oda", surface: "와서", stemEnd: 1, sense: "comes, so" },
      {
        wordId: "usan",
        surface: "우산을",
        stemEnd: 2,
        pronunciation: "우사늘",
      },
      { wordId: "sseuda", surface: "써요", stemEnd: 1, sense: "use" },
    ],
  },
  {
    id: "winter-cold",
    level: 1,
    korean: "겨울은 추워요.",
    english: "Winter is cold.",
    words: [
      {
        wordId: "gyeoul",
        surface: "겨울은",
        stemEnd: 2,
        pronunciation: "겨우른",
      },
      { wordId: "chupda", surface: "추워요", stemEnd: 2, sense: "is cold" },
    ],
  },
  {
    id: "summer-sea",
    level: 1,
    korean: "여름에는 바다에 가요.",
    english: "In summer I go to the sea.",
    words: [
      {
        wordId: "yeoreum",
        surface: "여름에는",
        stemEnd: 2,
        pronunciation: "여르메는",
      },
      { wordId: "bada", surface: "바다에", stemEnd: 2 },
      { wordId: "gada", surface: "가요", stemEnd: 1 },
    ],
  },
  {
    id: "weekend-rest",
    level: 1,
    korean: "주말에 집에서 쉬어요.",
    english: "I rest at home on the weekend.",
    words: [
      {
        wordId: "jumal",
        surface: "주말에",
        stemEnd: 2,
        pronunciation: "주마레",
      },
      { wordId: "jip", surface: "집에서", stemEnd: 1, pronunciation: "지베서" },
      { wordId: "swida", surface: "쉬어요", stemEnd: 1 },
    ],
  },
  {
    id: "sunday-park",
    level: 1,
    korean: "일요일에 공원에서 운동해요.",
    english: "On Sunday I exercise in the park.",
    words: [
      {
        wordId: "iryoil",
        surface: "일요일에",
        stemEnd: 3,
        pronunciation: "이료이레",
      },
      {
        wordId: "gongwon",
        surface: "공원에서",
        stemEnd: 2,
        pronunciation: "공워네서",
      },
      { wordId: "undonghada", surface: "운동해요", stemEnd: 3 },
    ],
  },
  {
    id: "headache-hospital",
    level: 1,
    korean: "머리가 아파서 병원에 가요.",
    english: "My head hurts, so I go to the hospital.",
    words: [
      { wordId: "meori", surface: "머리가", stemEnd: 2 },
      { wordId: "apeuda", surface: "아파서", stemEnd: 2, sense: "hurts, so" },
      {
        wordId: "byeongwon",
        surface: "병원에",
        stemEnd: 2,
        pronunciation: "병워네",
      },
      { wordId: "gada", surface: "가요", stemEnd: 1 },
    ],
  },
  {
    id: "pharmacy-where",
    level: 1,
    korean: "약국이 어디에 있어요?",
    english: "Where is the pharmacy?",
    words: [
      {
        wordId: "yakguk",
        surface: "약국이",
        stemEnd: 2,
        pronunciation: "약꾸기",
      },
      { wordId: "eodi", surface: "어디에", stemEnd: 2 },
      {
        wordId: "itda",
        surface: "있어요",
        stemEnd: 1,
        pronunciation: "이써요",
        sense: "is it",
      },
    ],
  },
  {
    id: "bank-post-office",
    level: 1,
    korean: "은행은 우체국 옆에 있어요.",
    english: "The bank is next to the post office.",
    words: [
      { wordId: "eunhaeng", surface: "은행은", stemEnd: 2 },
      { wordId: "ucheguk", surface: "우체국", stemEnd: 3 },
      {
        wordId: "yeop",
        surface: "옆에",
        stemEnd: 1,
        pronunciation: "여페",
        sense: "next to",
      },
      {
        wordId: "itda",
        surface: "있어요",
        stemEnd: 1,
        pronunciation: "이써요",
        sense: "is",
      },
    ],
  },
  {
    id: "station-walk",
    level: 1,
    korean: "역까지 걸어서 가요.",
    english: "I walk to the station.",
    words: [
      { wordId: "yeok", surface: "역까지", stemEnd: 1 },
      {
        wordId: "geotda",
        surface: "걸어서",
        stemEnd: 1,
        pronunciation: "거러서",
        sense: "on foot",
      },
      { wordId: "gada", surface: "가요", stemEnd: 1 },
    ],
  },
  {
    id: "time-now",
    level: 1,
    korean: "지금 몇 시예요?",
    english: "What time is it now?",
    words: [
      { wordId: "jigeum", surface: "지금", stemEnd: 2 },
      { wordId: "myeot", surface: "몇", stemEnd: 1 },
      { wordId: "si", surface: "시예요", stemEnd: 1, sense: "o'clock is it" },
    ],
  },
  {
    id: "store-clothes",
    level: 1,
    korean: "백화점에서 옷을 샀어요.",
    english: "I bought clothes at the department store.",
    words: [
      {
        wordId: "baekhwajeom",
        surface: "백화점에서",
        stemEnd: 3,
        pronunciation: "배콰저메서",
      },
      { wordId: "ot", surface: "옷을", stemEnd: 1, pronunciation: "오슬" },
      {
        wordId: "sada",
        surface: "샀어요",
        stemEnd: 1,
        pronunciation: "사써요",
        sense: "bought",
      },
    ],
  },
  {
    id: "shoes-small",
    level: 1,
    korean: "이 신발은 너무 작아요.",
    english: "These shoes are too small.",
    words: [
      { wordId: "i", surface: "이", stemEnd: 1 },
      {
        wordId: "sinbal",
        surface: "신발은",
        stemEnd: 2,
        pronunciation: "신바른",
      },
      { wordId: "neomu", surface: "너무", stemEnd: 2 },
      {
        wordId: "jakda",
        surface: "작아요",
        stemEnd: 1,
        pronunciation: "자가요",
        sense: "are small",
      },
    ],
  },
  {
    id: "call-mother",
    level: 1,
    korean: "저녁에 어머니께 전화해요.",
    english: "I call my mother in the evening.",
    words: [
      {
        wordId: "jeonyeok",
        surface: "저녁에",
        stemEnd: 2,
        pronunciation: "저녀게",
      },
      {
        wordId: "eomeoni",
        surface: "어머니께",
        stemEnd: 3,
        sense: "to (my) mother",
      },
      { wordId: "jeonhwahada", surface: "전화해요", stemEnd: 3 },
    ],
  },
  {
    id: "like-coffee",
    level: 1,
    korean: "저는 커피를 좋아해요.",
    english: "I like coffee.",
    words: [
      { wordId: "jeo", surface: "저는", stemEnd: 1 },
      { wordId: "keopi", surface: "커피를", stemEnd: 2 },
      {
        wordId: "joahada",
        surface: "좋아해요",
        stemEnd: 3,
        pronunciation: "조아해요",
      },
    ],
  },
  {
    id: "no-tea",
    level: 1,
    korean: "차는 안 마셔요.",
    english: "I don't drink tea.",
    words: [
      { wordId: "cha", surface: "차는", stemEnd: 1 },
      { wordId: "an", surface: "안", stemEnd: 1 },
      { wordId: "masida", surface: "마셔요", stemEnd: 2 },
    ],
  },
  {
    id: "puppy-cute",
    level: 1,
    korean: "강아지가 정말 귀여워요.",
    english: "The puppy is really cute.",
    words: [
      { wordId: "gangaji", surface: "강아지가", stemEnd: 3 },
      { wordId: "jeongmal", surface: "정말", stemEnd: 2 },
      {
        wordId: "gwiyeopda",
        surface: "귀여워요",
        stemEnd: 3,
        sense: "is cute",
      },
    ],
  },
  {
    id: "cat-sofa",
    level: 1,
    korean: "고양이가 소파에서 자요.",
    english: "The cat sleeps on the sofa.",
    words: [
      { wordId: "goyangi", surface: "고양이가", stemEnd: 3 },
      { wordId: "sopa", surface: "소파에서", stemEnd: 2 },
      { wordId: "jada", surface: "자요", stemEnd: 1 },
    ],
  },
  {
    id: "tired-early",
    level: 1,
    korean: "피곤해서 일찍 자요.",
    english: "I'm tired, so I go to bed early.",
    words: [
      {
        wordId: "pigonhada",
        surface: "피곤해서",
        stemEnd: 3,
        sense: "tired, so",
      },
      { wordId: "iljjik", surface: "일찍", stemEnd: 2 },
      { wordId: "jada", surface: "자요", stemEnd: 1 },
    ],
  },
  {
    id: "music-daily",
    level: 1,
    korean: "매일 음악을 들어요.",
    english: "I listen to music every day.",
    words: [
      { wordId: "maeil", surface: "매일", stemEnd: 2 },
      {
        wordId: "eumak",
        surface: "음악을",
        stemEnd: 2,
        pronunciation: "으마글",
      },
      {
        wordId: "deutda",
        surface: "들어요",
        stemEnd: 1,
        pronunciation: "드러요",
      },
    ],
  },
  {
    id: "photo-here",
    level: 1,
    korean: "여기에서 사진을 찍어요.",
    english: "I take photos here.",
    words: [
      { wordId: "yeogi", surface: "여기에서", stemEnd: 2 },
      {
        wordId: "sajin",
        surface: "사진을",
        stemEnd: 2,
        pronunciation: "사지늘",
      },
      {
        wordId: "jjikda",
        surface: "찍어요",
        stemEnd: 1,
        pronunciation: "찌거요",
      },
    ],
  },
  {
    id: "sibling-school",
    level: 1,
    korean: "동생은 고등학생이에요.",
    english: "My younger sibling is a high school student.",
    words: [
      { wordId: "dongsaeng", surface: "동생은", stemEnd: 2 },
      {
        wordId: "godeunghaksaeng",
        surface: "고등학생이에요",
        stemEnd: 4,
        pronunciation: "고등학쌩이에요",
        sense: "is a high school student",
      },
    ],
  },
  {
    id: "birthday-today",
    level: 1,
    korean: "오늘은 제 생일이에요.",
    english: "Today is my birthday.",
    words: [
      {
        wordId: "oneul",
        surface: "오늘은",
        stemEnd: 2,
        pronunciation: "오느른",
      },
      { wordId: "je", surface: "제", stemEnd: 1 },
      {
        wordId: "saengil",
        surface: "생일이에요",
        stemEnd: 2,
        pronunciation: "생이리에요",
        sense: "is (my) birthday",
      },
    ],
  },
  {
    id: "its-okay",
    level: 1,
    korean: "괜찮아요. 천만에요.",
    english: "It's fine. You're welcome.",
    words: [
      {
        wordId: "gwaenchanta",
        surface: "괜찮아요",
        stemEnd: 2,
        pronunciation: "괜차나요",
        sense: "it's fine",
      },
      {
        wordId: "cheonmaneyo",
        surface: "천만에요",
        stemEnd: 4,
        pronunciation: "천마네요",
      },
    ],
  },
  {
    id: "sorry-late",
    level: 1,
    korean: "늦어서 미안해요.",
    english: "Sorry I'm late.",
    words: [
      {
        wordId: "neutda",
        surface: "늦어서",
        stemEnd: 1,
        pronunciation: "느저서",
        sense: "late, so",
      },
      { wordId: "mianhada", surface: "미안해요", stemEnd: 3 },
    ],
  },
  {
    id: "work-week",
    level: 1,
    korean: "월요일부터 금요일까지 일해요.",
    english: "I work from Monday to Friday.",
    words: [
      {
        wordId: "woryoil",
        surface: "월요일부터",
        stemEnd: 3,
        pronunciation: "워료일부터",
      },
      {
        wordId: "geumyoil",
        surface: "금요일까지",
        stemEnd: 3,
        pronunciation: "그묘일까지",
      },
      { wordId: "ilhada", surface: "일해요", stemEnd: 2 },
    ],
  },
  {
    id: "korean-food",
    level: 1,
    korean: "한국 음식을 좋아해요.",
    english: "I like Korean food.",
    words: [
      { wordId: "hanguk", surface: "한국", stemEnd: 2 },
      {
        wordId: "eumsik",
        surface: "음식을",
        stemEnd: 2,
        pronunciation: "음시글",
      },
      {
        wordId: "joahada",
        surface: "좋아해요",
        stemEnd: 3,
        pronunciation: "조아해요",
      },
    ],
  },
  {
    id: "hungry",
    level: 1,
    korean: "배가 고파요.",
    english: "I'm hungry.",
    words: [
      { wordId: "bae", surface: "배가", stemEnd: 1 },
      {
        wordId: "gopeuda",
        surface: "고파요",
        stemEnd: 2,
        sense: "(my stomach) is hungry",
      },
    ],
  },
  {
    id: "thirsty",
    level: 1,
    korean: "목이 말라요. 물 주세요.",
    english: "I'm thirsty. Water, please.",
    words: [
      { wordId: "mok", surface: "목이", stemEnd: 1, pronunciation: "모기" },
      { wordId: "mareuda", surface: "말라요", stemEnd: 2, sense: "is dry" },
      { wordId: "mul", surface: "물", stemEnd: 1 },
      {
        wordId: "juda",
        surface: "주세요",
        stemEnd: 1,
        sense: "please give me",
      },
    ],
  },
  {
    id: "house-not-big",
    level: 1,
    korean: "우리 집은 크지 않아요.",
    english: "Our house isn't big.",
    words: [
      { wordId: "uri", surface: "우리", stemEnd: 2 },
      { wordId: "jip", surface: "집은", stemEnd: 1, pronunciation: "지븐" },
      { wordId: "keuda", surface: "크지", stemEnd: 1 },
      {
        wordId: "anta",
        surface: "않아요",
        stemEnd: 1,
        pronunciation: "아나요",
        sense: "is not",
      },
    ],
  },
  {
    id: "clean-room",
    level: 1,
    korean: "방을 청소해요.",
    english: "I clean my room.",
    words: [
      { wordId: "bang", surface: "방을", stemEnd: 1 },
      { wordId: "cheongsohada", surface: "청소해요", stemEnd: 3 },
    ],
  },
  {
    id: "open-window",
    level: 1,
    korean: "창문을 열어 주세요.",
    english: "Please open the window.",
    words: [
      {
        wordId: "changmun",
        surface: "창문을",
        stemEnd: 2,
        pronunciation: "창무늘",
      },
      { wordId: "yeolda", surface: "열어", stemEnd: 1, pronunciation: "여러" },
      {
        wordId: "juda",
        surface: "주세요",
        stemEnd: 1,
        sense: "please (do it for me)",
      },
    ],
  },
  {
    id: "close-door",
    level: 1,
    korean: "문을 닫아요.",
    english: "I close the door.",
    words: [
      { wordId: "mun", surface: "문을", stemEnd: 1, pronunciation: "무늘" },
      {
        wordId: "datda",
        surface: "닫아요",
        stemEnd: 1,
        pronunciation: "다다요",
      },
    ],
  },
  {
    id: "wash-hands",
    level: 1,
    korean: "밥 먹기 전에 손을 씻어요.",
    english: "I wash my hands before I eat.",
    words: [
      { wordId: "bap", surface: "밥", stemEnd: 1 },
      {
        wordId: "meokda",
        surface: "먹기",
        stemEnd: 1,
        pronunciation: "먹끼",
        sense: "eating",
      },
      {
        wordId: "jeon",
        surface: "전에",
        stemEnd: 1,
        pronunciation: "저네",
        sense: "before",
      },
      { wordId: "son", surface: "손을", stemEnd: 1, pronunciation: "소늘" },
      {
        wordId: "ssitda",
        surface: "씻어요",
        stemEnd: 1,
        pronunciation: "씨서요",
      },
    ],
  },
  {
    id: "sit-here",
    level: 1,
    korean: "여기 앉으세요.",
    english: "Please sit here.",
    words: [
      { wordId: "yeogi", surface: "여기", stemEnd: 2 },
      {
        wordId: "anda",
        surface: "앉으세요",
        stemEnd: 1,
        pronunciation: "안즈세요",
        sense: "please sit",
      },
    ],
  },
  {
    id: "shower-mornings",
    level: 1,
    korean: "아침마다 샤워를 해요.",
    english: "I shower every morning.",
    words: [
      {
        wordId: "achim",
        surface: "아침마다",
        stemEnd: 2,
        sense: "every morning",
      },
      { wordId: "syawo", surface: "샤워를", stemEnd: 2 },
      { wordId: "hada", surface: "해요", stemEnd: 1 },
    ],
  },
  {
    id: "korean-hard",
    level: 1,
    korean: "한국어는 조금 어려워요.",
    english: "Korean is a little difficult.",
    words: [
      {
        wordId: "hangugeo",
        surface: "한국어는",
        stemEnd: 3,
        pronunciation: "한구거는",
      },
      { wordId: "jogeum", surface: "조금", stemEnd: 2 },
      {
        wordId: "eoryeopda",
        surface: "어려워요",
        stemEnd: 3,
        sense: "is difficult",
      },
    ],
  },
  {
    id: "meet-tomorrow",
    level: 1,
    korean: "내일 친구를 만나요.",
    english: "I'm meeting a friend tomorrow.",
    words: [
      { wordId: "naeil", surface: "내일", stemEnd: 2 },
      { wordId: "chingu", surface: "친구를", stemEnd: 2 },
      { wordId: "mannada", surface: "만나요", stemEnd: 2 },
    ],
  },
  {
    id: "busy-yesterday",
    level: 1,
    korean: "어제는 정말 바빴어요.",
    english: "I was really busy yesterday.",
    words: [
      { wordId: "eoje", surface: "어제는", stemEnd: 2 },
      { wordId: "jeongmal", surface: "정말", stemEnd: 2 },
      {
        wordId: "bappeuda",
        surface: "바빴어요",
        stemEnd: 2,
        pronunciation: "바빠써요",
        sense: "was busy",
      },
    ],
  },
  {
    id: "new-car",
    level: 1,
    korean: "새 자동차를 샀어요.",
    english: "I bought a new car.",
    words: [
      { wordId: "sae", surface: "새", stemEnd: 1 },
      { wordId: "jadongcha", surface: "자동차를", stemEnd: 3 },
      {
        wordId: "sada",
        surface: "샀어요",
        stemEnd: 1,
        pronunciation: "사써요",
        sense: "bought",
      },
    ],
  },
  {
    id: "write-letter",
    level: 1,
    korean: "편지를 써요.",
    english: "I write a letter.",
    words: [
      { wordId: "pyeonji", surface: "편지를", stemEnd: 2 },
      { wordId: "sseuda", surface: "써요", stemEnd: 1, sense: "write" },
    ],
  },
]
