/**
 * Turning `git log --numstat` into a snapshot. The Node half of the feature:
 * `scripts/loc-snapshot.ts` runs git and writes the file, and everything it
 * decides lives here as pure functions over text so it can be tested without
 * a repository. Never imported by the bundle.
 *
 * What counts, and what does not:
 *
 * - **Humans only.** A commit whose author ends in `[bot]` (the release,
 *   changeset and dependency bots) is not the person's work.
 * - **Generated files are counted, but apart** (`genAdd`/`genDel`). A lockfile
 *   regenerated by one dependency bump can outweigh a month of real work, so
 *   the default view leaves them out; the widget's switch brings them back.
 * - **Each commit's own diff.** Merge commits have none, which is right for
 *   the squash-merge flow this repo uses and for a merge flow alike, since the
 *   commits they bring in are counted themselves.
 * - **By the day a commit landed**, in UTC.
 */

import { addDays } from "./dates.ts"
import type { LocSnapshot, RepoDay } from "./schema.ts"

/**
 * Days of history a snapshot carries: the longest range the widget offers (90)
 * and the 90 days before it, which its "vs previous period" line compares
 * against.
 *
 * This module imports nothing at runtime but `dates.ts`, on purpose: the
 * Docker release job runs the generator with Node and nothing installed, so
 * `zod` (which `schema.ts` loads) is out of reach there. The shape is checked
 * by this module's test instead.
 */
export const WINDOW_DAYS = 180

type FileStat = { path: string; added: number; removed: number }

export type CommitStat = {
  /** `YYYY-MM-DD`, UTC. */
  date: string
  author: string
  files: ReadonlyArray<FileStat>
}

/**
 * The log format `parseGitLog` reads: a record separator, the committer date,
 * a unit separator and the author name, then git's own `--numstat` lines.
 * Passed to `git log` as `--format`; kept here so the two cannot drift.
 */
export const GIT_LOG_FORMAT = "%x1e%cd%x1f%an"
export const GIT_LOG_DATE = "format-local:%Y-%m-%d"

const RECORD = "\u001e"
const FIELD = "\u001f"
const NUMSTAT_LINE = /^(\d+|-)\t(\d+|-)\t(.+)$/

/**
 * `git log` prints a rename as `old => new`, or `dir/{old => new}/file` when
 * the two share a prefix and suffix. The classifier wants the path the file
 * has now.
 */
export function expandRenamedPath(path: string): string {
  const braced = /^(.*)\{(.*) => (.*)\}(.*)$/.exec(path)
  if (braced !== null) {
    return `${braced[1]}${braced[3]}${braced[4]}`.replaceAll(/\/{2,}/g, "/")
  }
  const parts = path.split(" => ")
  return parts.length === 2 ? parts[1] : path
}

export function parseGitLog(raw: string): Array<CommitStat> {
  const commits: Array<CommitStat> = []
  for (const record of raw.split(RECORD)) {
    if (record.trim() === "") continue
    const [header = "", ...lines] = record.split("\n")
    const [date = "", author = ""] = header.split(FIELD)
    const files: Array<FileStat> = []
    for (const line of lines) {
      const match = NUMSTAT_LINE.exec(line)
      if (match === null) continue
      // A binary file reports `-` for both counts; it has no lines to count.
      files.push({
        path: expandRenamedPath(match[3]),
        added: match[1] === "-" ? 0 : Number(match[1]),
        removed: match[2] === "-" ? 0 : Number(match[2]),
      })
    }
    commits.push({ date, author, files })
  }
  return commits
}

export function isBot(author: string): boolean {
  return /\[bot\]$/i.test(author)
}

/**
 * Files nobody wrote by hand, across both repositories:
 *
 * - lockfiles;
 * - anything under a `generated/` directory or named `*.gen.*`
 *   (`routeTree.gen.ts`, `packages/server-routes/src/generated/routes.ts`);
 * - the route snapshot `routes.server.json`;
 * - `.sqlx/`, the server's offline query cache, and the server's
 *   `.github/docker-changesets/`;
 * - test snapshots, changelogs and built output.
 */
const GENERATED: ReadonlyArray<RegExp> = [
  /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|Cargo\.lock|bun\.lockb?)$/,
  /(^|\/)generated\//,
  /\.gen\.[cm]?[jt]sx?$/,
  /(^|\/)routes\.server\.json$/,
  /(^|\/)\.sqlx\//,
  /^\.github\/docker-changesets\//,
  /(^|\/)__snapshots__\//,
  /\.snap$/,
  /(^|\/)CHANGELOG\.md$/,
  /(^|\/)dist\//,
  /\.min\.(js|css)$/,
]

export function isGeneratedPath(path: string): boolean {
  return GENERATED.some((pattern) => pattern.test(path))
}

const NO_LINES: RepoDay = { add: 0, del: 0, genAdd: 0, genDel: 0 }

/**
 * One repository's lines per day, for the days from `from` through `through`.
 * The bounds are applied here as well as in the `--since` the script passes to
 * git, so a stray commit with a skewed clock does not reach the file.
 */
export function foldCommits(
  commits: ReadonlyArray<CommitStat>,
  from: string,
  through: string
): Map<string, RepoDay> {
  const days = new Map<string, RepoDay>()
  for (const commit of commits) {
    if (isBot(commit.author)) continue
    if (commit.date < from || commit.date > through) continue
    const day = days.get(commit.date) ?? { ...NO_LINES }
    for (const file of commit.files) {
      if (isGeneratedPath(file.path)) {
        day.genAdd += file.added
        day.genDel += file.removed
      } else {
        day.add += file.added
        day.del += file.removed
      }
    }
    days.set(commit.date, day)
  }
  return days
}

type RepoCommits = { name: string; commits: ReadonlyArray<CommitStat> }

export function assembleSnapshot({
  through,
  generatedAt,
  repos,
}: {
  through: string
  generatedAt: string
  repos: ReadonlyArray<RepoCommits>
}): LocSnapshot {
  const from = addDays(through, -(WINDOW_DAYS - 1))
  const byDate = new Map<string, Record<string, RepoDay>>()
  for (const repo of repos) {
    for (const [date, day] of foldCommits(repo.commits, from, through)) {
      byDate.set(date, { ...byDate.get(date), [repo.name]: day })
    }
  }
  const days = [...byDate]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([date, perRepo]) => ({ date, repos: perRepo }))
  return {
    version: 1,
    generatedAt,
    through,
    repos: repos.map((repo) => repo.name),
    days,
  }
}
