#!/usr/bin/env bash
set -euo pipefail

# Copies the Node and pnpm versions the flake provides into the places outside
# Nix that pin them, or checks that they already match.
#
#   .nvmrc                           <- node        (npm ships with it)
#   package.json "packageManager"    <- pnpm@<pnpm>
#   apps/www/Dockerfile "FROM node:" <- node's major
#   pnpm-lock.yaml packageManagerDependencies <- pnpm (via pnpm install)
#
# The flake is the source of truth: nix/node/default.nix picks the packages and
# exposes their versions as the `toolchain` flake output. These copies exist
# for what does not run inside `nix develop` (nvm/fnm, pnpm's own version
# switching, the Docker build), and drifted from it whenever one side moved
# without the other. Never edit them by hand: change nix/node or flake.lock,
# then run this script.
#
# flake-update.yml runs it after every `nix flake update`, and pr.yml runs it
# with --check, so a PR that moves one side alone fails.
#
# Usage:
#   scripts/sync-toolchain.sh           write the copies
#   scripts/sync-toolchain.sh --check   exit 1 if any copy differs

usage() {
  echo "usage: $0 [--check]" >&2
  exit 2
}

check=false
case $# in
  0) ;;
  1) [[ $1 == "--check" ]] || usage; check=true ;;
  *) usage ;;
esac

cd "$(dirname "$0")/.."

system=$(nix eval --impure --raw --expr builtins.currentSystem)
node=$(nix eval --raw ".#toolchain.$system.node")
pnpm=$(nix eval --raw ".#toolchain.$system.pnpm")
node_major=${node%%.*}

echo "flake toolchain: node $node, pnpm $pnpm"

# Each copy is one file and the sed program that rewrites it. Every program
# must match exactly one line, so a reformatted file fails loudly here
# instead of silently keeping a stale version.
files=(.nvmrc package.json apps/www/Dockerfile)
programs=(
  "s/^.*$/$node/"
  "s/^\(  \"packageManager\": \"pnpm@\)[^\"]*\(\",\)$/\1$pnpm\2/"
  "s/^\(FROM node:\)[0-9][0-9]*\(-alpine AS base\)$/\1$node_major\2/"
)
patterns=(
  '^.*$'
  '^  "packageManager": "pnpm@[^"]*",$'
  '^FROM node:[0-9][0-9]*-alpine AS base$'
)

drift=false
for i in "${!files[@]}"; do
  file=${files[$i]}
  matches=$(grep -c -- "${patterns[$i]}" "$file" || true)
  if [[ $matches -ne 1 ]]; then
    echo "error: expected one line matching '${patterns[$i]}' in $file, found $matches" >&2
    exit 1
  fi
  expected=$(sed -- "${programs[$i]}" "$file")
  if [[ $expected == "$(cat -- "$file")" ]]; then
    continue
  fi
  if $check; then
    drift=true
    diff -u --label "$file" --label "$file (from flake)" -- "$file" <(echo "$expected") || true
  else
    echo "$expected" >"$file"
    echo "updated $file"
  fi
done

# pnpm also locks its own binary in pnpm-lock.yaml (packageManagerDependencies,
# with integrity hashes), so that copy is regenerated by pnpm, not rewritten.
locked_pnpm=$(awk '/^    packageManagerDependencies:$/ { f = 1 } f && /^        version: / { print $2; exit }' pnpm-lock.yaml)
if [[ $locked_pnpm != "$pnpm" ]]; then
  if $check; then
    drift=true
    echo "pnpm-lock.yaml locks pnpm ${locked_pnpm:-(none)}, the flake provides $pnpm"
  else
    nix develop .#extension --command pnpm install --lockfile-only
    echo "updated pnpm-lock.yaml"
  fi
fi

if $drift; then
  echo "error: these copies differ from the flake's toolchain; run scripts/sync-toolchain.sh" >&2
  exit 1
fi
