#!/usr/bin/env bash
set -euo pipefail

# Copies paulgsc/server's route snapshot into the two places this repo keeps
# it, and optionally checks this repo against it.
#
#   packages/contract-harness/routes.server.json     <- dump-routes
#   packages/server-routes/src/generated/routes.ts   <- dump-routes -- --ts
#
# Both are generated by the server and never hand-edited (CLAUDE.md, "Cross-repo
# coupling"). This script is the only thing that should write them, and it is
# what the server's own CI calls (paulgsc/server .github/workflows/routes.yml):
# on every server PR, with --verify, so a route change that breaks a contract
# here fails on the server PR that made it; and on every server merge, without
# it, to open the sync PR in this repo. Keeping the destinations here, not in
# the server's workflow, means moving either file is a change to this repo
# alone.
#
# Usage:
#   scripts/sync-server-routes.sh <routes.server.json> <routes.server.ts> [--verify]
#
# --verify runs the two checks that read these files and need no server:
#   - @some-ui/server-routes' test: the JSON and the TS agree with each other
#   - contract:drift: every contract targets a route the server still serves

usage() {
  echo "usage: $0 <routes.server.json> <routes.server.ts> [--verify]" >&2
  exit 2
}

[[ $# -ge 2 && $# -le 3 ]] || usage
json_src=$1
ts_src=$2
verify=false
if [[ $# -eq 3 ]]; then
  [[ $3 == "--verify" ]] || usage
  verify=true
fi

for src in "$json_src" "$ts_src"; do
  [[ -s $src ]] || {
    echo "error: $src is missing or empty" >&2
    exit 1
  }
done

# Resolve the sources before changing directory, so relative paths still work.
json_src=$(realpath "$json_src")
ts_src=$(realpath "$ts_src")

cd "$(dirname "$0")/.."

json_dest=packages/contract-harness/routes.server.json
ts_dest=packages/server-routes/src/generated/routes.ts

cp "$json_src" "$json_dest"
cp "$ts_src" "$ts_dest"

if git diff --quiet -- "$json_dest" "$ts_dest"; then
  echo "Route snapshot unchanged."
else
  echo "Route snapshot changed:"
  git --no-pager diff --stat -- "$json_dest" "$ts_dest"
fi

if [[ $verify == true ]]; then
  pnpm --filter @some-ui/server-routes test
  pnpm --filter @some-ui/contract-harness contract:drift
fi
